"""second migration

Revision ID: 39a39a83b4bb
Revises: 86ac3f8e790b
Create Date: 2016-07-29 16:21:48.829697

"""

# revision identifiers, used by Alembic.
revision = '39a39a83b4bb'
down_revision = '86ac3f8e790b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
